name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  cI:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
        
    - name: Run Tests With Jacoco Coverage
      run: mvn -B -f pom.xml test jacoco:prepare-agent jacoco:report
    
    - name: SonarCloud Analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn -B verify sonar:sonar \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.organization=lucasarags \
        -Dsonar.projectKey=lucasarags_java-api \
        -Dsonar.language=java \
        -Dsonar.java.coveragePlugin=jacoco \
        -Dmaven.test.skip=true
